on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - data/**
      - lib/**
      - po/**
      - src/**
      - subprojects/**
      - vapi/**
      - meson.build
      - meson_options.txt

name: Build Artifacts

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged

    strategy:
      matrix: { target: [x86_64, aarch64] }
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Build Replay
        uses: ./.github/actions/build-replay
        with:
          target: ${{ matrix.target }}
          upload-artifact: true
          artifact-name: app.drey.Replay.flatpak
