on:
  schedule:
    - cron: '0 7 */7 * *' # This should run once a week

name: Docker image

jobs:
  build:
    name: Build and push the Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: build-aux/docker
          file: build-aux/docker/Dockerfile
          tags: nahuelwexd/replay-ci-image:latest
          pull: true
          push: true
          allow: security.insecure
